import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google"
import "./globals.css";
import { TaskProvider } from "./context/TaskContext";
import { Header } from "./components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});


export const metadata: Metadata = {
  title: "TODO App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TaskProvider>
      <html lang="en">
        <body
          className={`${josefinSans.className} antialiased dark:bg-darkBg bg-lightBg transition-colors duration-300 ease-in`}
        >
          <Header />
          <main>
            {children}
          </main>
          <ToastContainer />
        </body>
      </html>
    </TaskProvider>
  );
}
