import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google"
import "./globals.css";
import { Header } from "./components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./Providers";
import { ThemeProviders } from "./ThemeProvider";
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});


export const metadata: Metadata = {
  title: "TODO App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {

  return (

    <html lang="en" suppressHydrationWarning>
      <body
        className={`${josefinSans.className} antialiased `}
      >
        <Providers>
          <ThemeProviders>
            {/* <ThemeProvider attribute='class' defaultTheme="light" enableSystem> */}

            <Header />
            <main className="dark:bg-darkBg bg-lightBg transition-colors duration-300 ease-in">
              {children}
            </main>
            <ToastContainer />
            {/* </ThemeProvider> */}
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  );
}
