import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google"
import "./globals.css";
// import { TaskProvider } from "./context/TaskContext";
import { Header } from "./components/Header";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "./Providers";
import { ThemeProvider } from "./context/ThemeContext";
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
});


export const metadata: Metadata = {
  title: "TODO App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {

  return (

    <html lang="en">
      <body
        className={`${josefinSans.className} antialiased dark:bg-darkBg bg-lightBg transition-colors duration-300 ease-in`}
      >
        <Providers>
          <ThemeProvider>

            {/* <TaskProvider> */}
            <Header />
            {/* <Suspense fallback={<TaskSkeleton />}> */}
            <main>
              {children}
              {/* <Login /> */}
            </main>
            {/* </Suspense> */}
            <ToastContainer />
            {/* </TaskProvider> */}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
